# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys
import glob
import serial

import monitor_serial as ser

# avaliable port detection
def list_ports():
    if sys.platform.startswith('win'):
        ports = ['COM%s' % (i + 1) for i in range(256)]
    elif sys.platform.startswith('linux') or sys.platform.startswith('cygwin'):
        ports = glob.glob('/dev/tty[A-Za-z]*')
    elif sys.platform.startswith('darwin'):
        ports = glob.glob('/dev/tty.*')
    else:
        raise EnvironmentError('Unsupported platform')
    result = []
    for port in ports:
        try:
            s = serial.Serial(port)
            s.close()
            result.append(port)
        except (OSError, serial.SerialException):
            pass
    return result

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.BaudrateInput = QtWidgets.QLineEdit(self.centralwidget)
        self.BaudrateInput.setGeometry(QtCore.QRect(810, 80, 191, 22))
        self.BaudrateInput.setObjectName("BaudrateInput")
        self.BaudrateInput.setText("9600")

        self.PortBox = QtWidgets.QComboBox(self.centralwidget)
        self.PortBox.setGeometry(QtCore.QRect(810, 30, 191, 22))
        self.PortBox.setObjectName("PortBox")
        # add avaliable ports to list
        for port in list_ports():
            self.PortBox.addItem(port, port)

        self.PortLabel = QtWidgets.QLabel(self.centralwidget)
        self.PortLabel.setGeometry(QtCore.QRect(810, 10, 191, 16))
        self.PortLabel.setObjectName("PortLabel")

        self.BaudrateLabel = QtWidgets.QLabel(self.centralwidget)
        self.BaudrateLabel.setGeometry(QtCore.QRect(810, 60, 111, 16))
        self.BaudrateLabel.setObjectName("BaudrateLabel")

        self.ParityBox = QtWidgets.QComboBox(self.centralwidget)
        self.ParityBox.setGeometry(QtCore.QRect(810, 130, 191, 22))
        self.ParityBox.setObjectName("ParityBox")
        self.ParityBox.addItem("")
        self.ParityBox.addItem("")
        self.ParityBox.addItem("")
        self.ParityBox.addItem("")
        self.ParityBox.addItem("")

        self.StopbitBox = QtWidgets.QComboBox(self.centralwidget)
        self.StopbitBox.setGeometry(QtCore.QRect(810, 180, 191, 22))
        self.StopbitBox.setObjectName("StopbitBox")
        self.StopbitBox.addItem("")
        self.StopbitBox.addItem("")
        self.StopbitBox.addItem("")

        self.BytesizeBox = QtWidgets.QComboBox(self.centralwidget)
        self.BytesizeBox.setGeometry(QtCore.QRect(810, 230, 191, 22))
        self.BytesizeBox.setObjectName("BytesizeBox")
        self.BytesizeBox.addItem("")
        self.BytesizeBox.addItem("")
        self.BytesizeBox.addItem("")
        self.BytesizeBox.addItem("")

        self.ParityLabel = QtWidgets.QLabel(self.centralwidget)
        self.ParityLabel.setGeometry(QtCore.QRect(810, 110, 55, 16))
        self.ParityLabel.setObjectName("ParityLabel")

        self.sfcBox = QtWidgets.QCheckBox(self.centralwidget)
        self.sfcBox.setGeometry(QtCore.QRect(810, 260, 161, 21))
        self.sfcBox.setObjectName("sfcBox")

        self.rtsctsBox = QtWidgets.QCheckBox(self.centralwidget)
        self.rtsctsBox.setGeometry(QtCore.QRect(810, 290, 81, 20))
        self.rtsctsBox.setObjectName("rtsctsBox")

        self.dsrdtrBox = QtWidgets.QCheckBox(self.centralwidget)
        self.dsrdtrBox.setGeometry(QtCore.QRect(810, 320, 81, 20))
        self.dsrdtrBox.setObjectName("dsrdtrBox")

        self.StopbitsLabel = QtWidgets.QLabel(self.centralwidget)
        self.StopbitsLabel.setGeometry(QtCore.QRect(810, 160, 55, 16))
        self.StopbitsLabel.setObjectName("StopbitsLabel")

        self.BytesizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.BytesizeLabel.setGeometry(QtCore.QRect(810, 210, 111, 16))
        self.BytesizeLabel.setObjectName("BytesizeLabel")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(780, 10, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.TextWindow = QtWidgets.QTextEdit(self.centralwidget)
        self.TextWindow.setGeometry(QtCore.QRect(20, 10, 751, 551))
        self.TextWindow.setObjectName("TextWindow")

        self.OpenButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.open_on_click())
        self.OpenButton.setGeometry(QtCore.QRect(810, 350, 191, 28))
        self.OpenButton.setObjectName("OpenButton")

        self.CloseButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.close_on_click())
        self.CloseButton.setGeometry(QtCore.QRect(810, 390, 191, 28))
        self.CloseButton.setObjectName("CloseButton")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1056, 26))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PortLabel.setText(_translate("MainWindow", "Port"))
        self.BaudrateLabel.setText(_translate("MainWindow", "Baudrate"))
        self.ParityBox.setItemText(0, _translate("MainWindow", "NONE"))
        self.ParityBox.setItemText(1, _translate("MainWindow", "EVEN PARITY"))
        self.ParityBox.setItemText(2, _translate("MainWindow", "ODD PARITY"))
        self.ParityBox.setItemText(3, _translate("MainWindow", "MARK PARITY"))
        self.ParityBox.setItemText(4, _translate("MainWindow", "SPACE PARITY"))
        self.StopbitBox.setItemText(0, _translate("MainWindow", "ONE"))
        self.StopbitBox.setItemText(1, _translate("MainWindow", "ONE POINT FIVE"))
        self.StopbitBox.setItemText(2, _translate("MainWindow", "TWO"))
        self.BytesizeBox.setItemText(0, _translate("MainWindow", "8"))
        self.BytesizeBox.setItemText(1, _translate("MainWindow", "7"))
        self.BytesizeBox.setItemText(2, _translate("MainWindow", "6"))
        self.BytesizeBox.setItemText(3, _translate("MainWindow", "5"))
        self.ParityLabel.setText(_translate("MainWindow", "Parity"))
        self.sfcBox.setText(_translate("MainWindow", "Software flow controll"))
        self.rtsctsBox.setText(_translate("MainWindow", "RTC/CTS"))
        self.dsrdtrBox.setText(_translate("MainWindow", "DSR/DTR"))
        self.StopbitsLabel.setText(_translate("MainWindow", "StopBits"))
        self.BytesizeLabel.setText(_translate("MainWindow", "Byte Size"))
        self.OpenButton.setText(_translate("MainWindow", "Open/Change"))
        self.CloseButton.setText(_translate("MainWindow", "Close"))

    # open the serial port for reading and writing
    def open_on_click(self):
        temp_list = [self.PortBox.currentData(),self.BaudrateInput.text(),self.BytesizeBox.currentIndex(),
            self.ParityBox.currentIndex(), self.StopbitBox.currentIndex(), self.sfcBox.isChecked(),
            self.rtsctsBox.isChecked(), self.dsrdtrBox.isChecked()]
        print(temp_list)

    def close_on_click(self):
        raise NotImplementedError